version: "3.9"

services:
  react-app:
    build: .
    ports:
      - "3000:80"
    container_name: my-react-app
    restart: always
    volumes:
      - ./logs:/var/log/nginx  # Map Nginx logs to host for CloudWatch

