name: Deploy Staging React App

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      STAGING_IP: ${{ secrets.STAGING_IP }}
      STAGING_KEY: ${{ secrets.STAGING_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.STAGING_IP }}
          username: ubuntu
          key: ${{ env.STAGING_KEY }}
          script: |
            cd ~/my-react-app-staging || git clone -b staging https://github.com/vommidapuchinni/my-react-app.git ~/my-react-app-staging
            cd ~/my-react-app-staging
            git reset --hard
            git clean -fd
            git pull origin staging
            docker-compose -f docker-compose-staging.yml down
            docker-compose -f docker-compose-staging.yml up -d --build
            sudo amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/home/ubuntu/my-react-app-staging/cloudwatch-staging.json -s

