name: React Docker CI/CD Production

on:
  push:
    branches:
      - main  # Triggers only on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Lint & Test
      - name: Lint & Test
        run: |
          npm run lint || echo "No lint script found"
          npm test || echo "No tests found"

      # 5️⃣ Build React App
      - name: Build React App
        run: npm run build

      # 6️⃣ Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 7️⃣ Deploy to Production EC2
      - name: Deploy to Production EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << EOF
          cd ~/my-react-app
          docker-compose down
          docker-compose up -d --build
          EOF

